name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Mohfazam  # Replace with your GitHub username
          outputs: dist/snake.svg

      - name: Upload Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
